#
# Cookbook Name:: backendless_chef
# Recipe:: sync
#
# Copyright 2016, Hearst Automation Team
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

# For existing installs
execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/pivotal.pem" do
  action :run
  cwd '/'
  only_if { node['backendless_chef']['install']['existing'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/private-chef-secrets.json" do
  action :run
  cwd '/'
  only_if { node['backendless_chef']['install']['existing'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/webui_priv.pem" do
  action :run
  cwd '/'
  only_if { node['backendless_chef']['install']['existing'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/webui_pub.pem" do
  action :run
  cwd '/'
  only_if { node['backendless_chef']['install']['existing'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

# For new installs, should force a wait for the items to be generated by the faux master
execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/pivotal.pem" do
  action :run
  cwd '/'
  retries 4
  retry_delay 300
  not_if { node['backendless_chef']['install']['existing'] }
  only_if { node['backendless_chef']['master'] != node['fqdn'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/private-chef-secrets.json" do
  action :run
  cwd '/'
  retries 4
  retry_delay 300
  not_if { node['backendless_chef']['install']['existing'] }
  only_if { node['backendless_chef']['master'] != node['fqdn'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/webui_priv.pem" do
  action :run
  cwd '/'
  retries 4
  retry_delay 300
  not_if { node['backendless_chef']['install']['existing'] }
  only_if { node['backendless_chef']['master'] != node['fqdn'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end

execute "tar -zxvf #{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz etc/opscode/webui_pub.pem" do
  action :run
  cwd '/'
  retries 4
  retry_delay 300
  not_if { node['backendless_chef']['install']['existing'] }
  only_if { node['backendless_chef']['master'] != node['fqdn'] }
  only_if { File.exists?("#{node['backendless_chef']['s3']['dir']}/core_bundle.tar.gz") }
end
