name 'backendless_chef'
maintainer 'Hearst Automation Team'
maintainer_email 'atat@hearst.com'
source_url 'https://github.com/HearstAT/backendless_chef'
issues_url 'https://github.com/HearstAT/backendless_chef/issues'
license 'MIT'
description 'Installs/Configures backendless_chef'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '1.0.0'

depends 'python'
depends 'citadel'
depends 'newrelic'
depends 'newrelic_meetme_plugin'
depends 'sumologic-collector'
depends 'apt-chef'
depends 'chef-client'
